# Generated by Django 4.2.2 on 2023-11-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('seller', models.BigIntegerField()),
                ('productName', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('product_name', models.CharField(max_length=50)),
                ('quanteaty', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=20, null=True)),
                ('street', models.CharField(max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=20, null=True)),
                ('street', models.CharField(max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
            ],
        ),
    ]
