# Generated by Django 4.2.2 on 2023-10-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_products_quanteaty'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
