# Generated by Django 4.2.2 on 2023-11-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_rename_sellers_products_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default=324.234, max_length=50),
            preserve_default=False,
        ),
    ]
