# Generated by Django 4.2.2 on 2023-11-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_remove_carts_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='user',
            field=models.BigIntegerField(default=8655465),
            preserve_default=False,
        ),
    ]
